### ISSUE TITLE
Scrape from browser DOM

### ISSUE THREAD

**Issue by Matthias84** [SamR1/rdltr#8]
I like to ask, if it would be possible to add an feature that doesn't scrape the article content on server side, but allows to submit the browser DOM / HTML directly. This would allow to submit content via browser extension and to support fetching content behind paywals/ logins / user agent hacks / ...

(This is an pending [feature from wallabag](https://github.com/wallabag/wallabag/issues/3925))

**Comment by SamR1** [comment]
Hi,

Sorry for my late response, and thanks for your feedback.

Indeed, some of the articles I have saved do not display content due to server-side scraping limitations.
I add this issue on future developments (which are not yet planned for now).

**Comment by SamR1** [comment]
It's now possible to add content from browser side with a Firefox Add-on: 
https://addons.mozilla.org/en-US/firefox/addon/rdltr/
![popup screenshot](https://raw.githubusercontent.com/SamR1/rdltr-addon/master/misc/popup.png)

GitHub repo: https://github.com/SamR1/rdltr-addon
